### ISSUE TITLE
Create screenshots for README, how to get webhook link

### ISSUE THREAD

**Issue by agorlov** [agorlov/discordmsg#1]

**Comment by agorlov** [comment]
Open chanel preferences (if you have enough permissions):
![image](https://user-images.githubusercontent.com/2485728/43675882-27431cc0-97f0-11e8-8092-917494a87bd3.png)

Create Webhook:
![image](https://user-images.githubusercontent.com/2485728/43675886-33ca6872-97f0-11e8-93d9-1a48c35843a9.png)

**Comment by Ased2235** [comment]
Click edit and then copy Webhook url 
![image](https://user-images.githubusercontent.com/13244139/52475484-a854a680-2bac-11e9-8e67-e29f6aef5766.png)
