### ISSUE TITLE
Notify user in discord

### ISSUE THREAD

**Issue by bricecarbou** [agorlov/discordmsg#3]
Hello,

I use your functions,but I can't notify user when I sent a meassage to discro. Coudl you help me perhaps?

**Comment by agorlov** [comment]
User should subscribe to channel to get nottified.

**Comment by bricecarbou** [comment]
I find my answer :)

**Comment by bricecarbou** [comment]
To notify anybody by webhook, we need to use the "real" id of user (recover in discord with @\<username>) and use $msg="<@id_recovered> ..."

**Comment by agorlov** [comment]
Show please code example.

**Comment by bricecarbou** [comment]
$msg = "<@4386638385456546554> is notified";
 (new \AG\DiscordMsg(
            $msg, // message
            $webhookurl, // chanel webhook link
            "Trad Bot", // bot name
            '' // avatar url
        ))->send();

**Comment by agorlov** [comment]
Thank you!
